//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCaducidadesPromotor.AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacena
    {
        public int IdTienda { get; set; }
        public int IdProducto { get; set; }
        public int IdUsuarioAlta { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int IdUsuarioModifico { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Tienda Tienda { get; set; }
    }
}
